version: '3'
services:
  &postgres postgres:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nimda
      POSTGRES_DB: admin
    volumes:
      - "./db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "admin"]
      interval: 15s
      timeout: 5s
      retries: 4

  backend:
    build: ./go_backend
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: nimda
      POSTGRES_DB: admin
      POSTGRES_HOST: *postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build: ./FrontEnd-Angular/GQM
    ports:
      - "4200:4200"
    depends_on:
      - backend
