name: Build GQM Docker images

on:
  push:
    branches:
      - main
      - develop
      - frontend
      - backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch full history
        run: git fetch --prune --unshallow

      - name: Setup docker build tool
        uses: docker/setup-buildx-action@v2

      - name: Prepare docker-layer cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to docker.io
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version tag
        run: |
          BRANCH_NAME=${{ github.ref_name }}
          if [[ "$BRANCH_NAME" == "main" ]]; then
            echo "VERSION=1.${{ github.run_number }}.0" >> $GITHUB_ENV
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            echo "VERSION=0.${{ github.run_number }}.0" >> $GITHUB_ENV
          else
            echo "VERSION=0.0.${{ github.run_number }}" >> $GITHUB_ENV
          fi

      - name: Check for code changes
        run: |
          echo "Checking for changes..."
          FRONTEND_CHANGED=$(git diff --name-only HEAD^ HEAD | grep '^FrontEnd-Angular/GQM/' > /dev/null && echo "true" || echo "false")
          BACKEND_CHANGED=$(git diff --name-only HEAD^ HEAD | grep '^go_backend/' > /dev/null && echo "true" || echo "false")
          echo "FRONTEND_CHANGED=${FRONTEND_CHANGED}" >> $GITHUB_ENV
          echo "BACKEND_CHANGED=${BACKEND_CHANGED}" >> $GITHUB_ENV

      - name: Build and push Frontend
        if: env.FRONTEND_CHANGED == 'true'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gqm-frontend:${{ env.VERSION }} -t ${{ secrets.DOCKER_USERNAME }}/gqm-frontend:latest ./FrontEnd-Angular/GQM
          docker push ${{ secrets.DOCKER_USERNAME }}/gqm-frontend:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/gqm-frontend:latest

      - name: Build and push Backend
        if: env.BACKEND_CHANGED == 'true'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gqm-backend:${{ env.VERSION }} -t ${{ secrets.DOCKER_USERNAME }}/gqm-backend:latest ./go_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/gqm-backend:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/gqm-backend:latest
