name: build on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker-layer cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: docker.io login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build/push frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gqm-frontend:latest ./FrontEnd-Angular/GQM
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: build/push backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gqm-backend:latest ./go_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
