name: build on push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker buildx
        uses: docker/setup-buildx-action@v2

      - name: docker-layer cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: docker.io login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: set tag
        run: echo "VERSION=${{ github.run_number }}" >> $GITHUB_ENV

      - name: check frontend
        id: frontend-check
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^FrontEnd-Angular/GQM/' || echo "no changes" > /dev/null

      - name: check backend
        id: backend-check
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^go_backend/' || echo "no changes" > /dev/null

      - name: frontend build / push
        if: steps.frontend-check.outcome == 'success'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gqm-frontend:0.${{ env.VERSION }}.0 -t ${{ secrets.DOCKER_USERNAME }}/gqm-frontend:latest ./FrontEnd-Angular/GQM
          docker push ${{ secrets.DOCKER_USERNAME }}/gqm-frontend:0.${{ env.VERSION }}.0
          docker push ${{ secrets.DOCKER_USERNAME }}/gqm-frontend:latest

      - name: backend build / push
        if: steps.backend-check.outcome == 'success'
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/gqm-backend:0.${{ env.VERSION }}.0 -t ${{ secrets.DOCKER_USERNAME }}/gqm-backend:latest ./go_backend
          docker push ${{ secrets.DOCKER_USERNAME }}/gqm-backend:0.${{ env.VERSION }}.0
          docker push ${{ secrets.DOCKER_USERNAME }}/gqm-backend:latest
